export const list = [
    {
      id: 1,
      title: "Challenge 1",
      url: "/challenges/challenge1",
      img: "/Challenge-1.png",
      classIMG: "",
      alt: "Imagen del challenge 1",
      text: "Componente de Rating interactuable para puntuar, capaz reestablecerse el valor del mismo al volverlo a clicklear y fácil de usar para los usuarios",
    },
    {
      id: 2,
      title: "Challenge 2",
      url: "/challenges/challenge2",
      img: "/Challenge-2.png",
      classIMG: "",
      alt: "Imagen del challenge 2",
      text: "Caja de comentarios de varios niveles, capaz de agragar nuevos comentarios ya sea nuevos y responderle generando un nivel de profundidad",
    },
    {
      id: 3,
      title: "Challenge 3",
      url: "/challenges/challenge3",
      img: "/Challenge-3.png",
      classIMG: "w-48 h-48 place-self-center",
      alt: "Imagen del challenge 3",
      text: "Entrada con funcionalidad de autocompletado para encontrar la búsqueda de ciertos datos",
    },
     {
      id: 4,
      title: "Challenge 4",
      url: "/challenges/challenge4",
      img: "/Challenge-4.png",
      classIMG: "",
      alt: "Imagen del challenge 4",
      text: "To-Do-List funcional capaz de realizar operaciones CRUD y almacenar los datos",
    },
     {
      id: 5,
      title: "Challenge 5",
      url: "/challenges/challenge5",
      img: "/Challenge-5.png",
      classIMG: "",
      alt: "Imagen del challenge 5",
      text: "Barra de progreso simple, similar a las barras de carga progresivo",
    },
    {
      id: 6,
      title: "Challenge 6",
      url: "/challenges/challenge6",
      img: "/Challenge-6.png",
      classIMG: "w-48 h-48 place-self-center",
      alt: "Imagen del challenge 6",
      text: "Juego de Tic-Tac-Toe simple y funcional.",
    },
    {
      id: 7,
      title: "Challenge 7",
      url: "/challenges/challenge7",
      img: "/Challenge-7.png",
      classIMG: "w-48 h-48 place-self-center",
      alt: "Imagen del challenge 6",
      text: "Temporizador capaz de hacer cuenta regresiva e incluso parar en medio de la misma.",
    }
]